config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  resources :requests
  resources :events
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :admin, class_name: 'User'
	belongs_to :quarter
	has_many :recrutements
	has_many :members, class_name: 'User'
	has_many :participants, through: :recrutements
	has_many :events
	has_one_attached :picture
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
        @club = Club.find(params[:id])
  end

  # GET /clubs/new
  def new 
    @user = current_user
        @quarters = Quarter.all
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
    @quarters = Quarter.all
  end

  # POST /clubs
  # POST /clubs.json
  def create
      @my_user = current_user.id
    @club = Club.create('name' => params[:name], 'category' => params[:category], quarter_id: params[:quarter_id])

  @club.admin_id =  @my_user

    respond_to do |format|
      if @club.save
        format.html { redirect_to new_club_picture_path(@club.id), notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])
    puts "*"*60
    puts params
    respond_to do |format|
      if @club.update(name: params['name'], category: params['category'])
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(name: params['name'], category: params['category'])
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= form_with(model: club, local: true) do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
        <% club.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= form_tag url_for(action: 'create'), method: "club" do %>
<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

   <div class="field">
    <%= label_tag :name %>
    <%= text_area_tag :name, @club.name %>
  </div>


   <div class="field">
    <%= label_tag :category %>
    <%= text_area_tag :category, @club.category %>
  </div>

 

<div class="form-group">
   <label>Quarter</label>
   <%=select_tag 'quarter_id', options_for_select(@quarters.collect{ |t| [t.name, t.id] }), class:'form-control'%>
 </div>


  <div class="actions">
     <%= submit_tag "Create club" %>
  </div>
<% end %>
<% end %>

app/views/clubs/_update.html.erb
   <%= form_tag url_for(action: 'update'), method: "patch" do |form|%>
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >


  <div class="field">
    <%= label_tag :name %>
    <%= text_area_tag :name, @club.name %>
  </div>


   <div class="field">
    <%= label_tag :category %>
    <%= text_area_tag :category, @club.category %>
  </div>
  <div class="form-group">
   <label>Quarter</label>
   <%=select_tag 'quarter_id', options_for_select(@quarters.collect{ |t| [t.name, t.id] }), class:'form-control'%>
 </div>

  
<div class="field">
    <input type="hidden" name="club_id" value="<%= @club.id%>">
  </div>



  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'update', club: @club %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Liste des Clubs</h1>

<% if user_signed_in? %>
 <% a = 0 %>

<% @clubs.each do |club| %>

​

  <% if club.admin.id == current_user.id %>

  <h2><%= link_to 'Mon club', club_path(club.id) %></h2>

    

  <% else %>

    <% a+= 1%>

  <% end %>

<% end %>

<%if a == @clubs.count %>

  <h1><%= link_to 'Créer un club', new_club_path %></h1>

  

<% end %>
<%end%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= club.category %></td>
        <td><%= link_to 'Afficher', club %></td>

        <% if user_signed_in? && current_user.role === 'admin' %>
                <td><a href="#" data-clubid ="<%=@club.id%>" data-quarterid="<%=@club.quarter_id%>" class="club_edit">Edit</a></td>
                <td><%= link_to 'Supprimer', club, method: :delete, data: { confirm: 'Voulez vous vraiment supprimer ce club?' } %></td>
        <%end%>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>



	<%if @club.picture.attached?%>
    	<%= image_tag @club.picture, alt: 'picture' ,:height => '300px',:width => '600px'%>
  <%else%>
    <p>=== Il n'y a pas encore de photos lié à cet club ===</p>
  <%end%>

  <% if current_user == @club.admin %>
    <h5>Changer de picture ?</h5>
      <%= form_tag club_pictures_path(@club.id), multipart: true do %>
      <%= file_field_tag :picture %>
      <%= submit_tag "mettre à jour" %>
    <% end %>
  <% end %>




<p id="notice"><%= notice %></p>



<li>  <a href="#" id="<%= @club.id %>" class="envoi">creer recrutement</a></li>

 <li> <a href="#" id="<%= @club.id %>" class="lasa">creer evenement</a></li>



<div class="jumbotron">
    <div class="container">

   <h1 class="display-5">Hello! vous etes sur le profil du club   <%= @club.name %> , de category:    <%= @club.category %></h1>

  </div>
  </div>

<main role="main">

<div class="jumbotron">
	  <div class="container text-center">

      <h1 class="display-3 text-primary">Listes recrutement creer</h1>
  </div>  </div>


      <div class="container">
        <!-- Example row of columns -->
        <div class="row d-flex justify-content-around">
      

    <% @club.recrutements.each do |recrutement| %>

    <div class="col-md-5 border border-primary shadow p-3 mb-5 bg-white rounded">



 <%= link_to recrutement.content, recrutement %>
     
    </div>
    <%end%>
  </div>



<div class="jumbotron">
	  <div class="container text-center">

      <h1 class="display-3 text-primary">Les membres du club</h1>
  </div>  </div>
<% @club.members.each do |member|%>
<h3 align="center"><%= member.first_name%> <%= member.last_name%></h3> 
<% end %>




<div class="jumbotron">
	  <div class="container text-center">

      <h1 class="display-3 text-primary">Les evenements du club</h1>
  </div>  </div>
<% @club.events.each do |event|%>
<h3 align="center"><%= link_to "#{event.title}", event_path(event.id)%></h3>
<% end %>



<% if user_signed_in? && current_user.role === 'admin' %>
<a href="#" data-clubid ="<%=@club.id%>" data-quarterid="<%=@club.quarter_id%>" class="club_edit">Edit</a> |
<%= link_to 'Back', clubs_path %>
<% end %>
<br><br>