config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  resources :requests
  resources :events
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :admin, class_name: 'User'
	belongs_to :quarter
	has_many :recrutements
	has_many :members, class_name: 'User'
	has_many :participants, through: :recrutements
	has_many :events
	has_one_attached :picture
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :club
end

app/models/quarter.rb
class Quarter < ApplicationRecord
	has_many :clubs
	has_many :users
end

app/models/recrutement.rb
class Recrutement < ApplicationRecord
	has_many :requests
	belongs_to :club
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :recrutement
	belongs_to :user
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         belongs_to :quarter, optional: true
         belongs_to :club, optional: true
         has_many :requests
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@quarters = Quarter.all
  	@clubs = Club.all
  	@events = Event.all
  	@recrutements = Recrutement.all
  	@requests = Request.all
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
        @club = Club.find(params[:id])
  end

  # GET /clubs/new
  def new 
    @user = current_user
        @quarters = Quarter.all
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
    @quarters = Quarter.all
  end

  # POST /clubs
  # POST /clubs.json
  def create
      @my_user = current_user.id
    @club = Club.create('name' => params[:name], 'category' => params[:category], quarter_id: params[:quarter_id])

  @club.admin_id =  @my_user

    respond_to do |format|
      if @club.save
        format.html { redirect_to new_club_picture_path(@club.id), notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])
    puts "*"*60
    puts params
    respond_to do |format|
      if @club.update(name: params['name'], category: params['category'])
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(name: params['name'], category: params['category'])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
   @event = Event.new
     @club = Club.find(params['data_value'])
  end

  # GET /events/1/edit
  def edit
    @recrutement = Recrutement.find(params['id'])
  end

  # POST /events
  # POST /events.json
  def create
  
    @event = Event.create('start_date' => params[:start_date], 'duration' => params[:duration], 'title' => params[:title], 'description' => params[:description], 'price' => params[:price],  'location' => params[:location],  club_id: params['club_id'])


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update(start_date: params['start_date'] , duration: params['duration'], title: params['title'], description: params['description'], price: params['price'], location: params['location'])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(start_date: params['start_date'] , duration: params['duration'], title: params['title'], description: params['description'], price: params['price'], location: params['location'])
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  def new
    @club = Club.find(params[:club_id])
  end

  def create
    @club = Club.find(params[:club_id])
    # @club.picture.attach(params[:picture])
    if params[:picture] != nil
      @club.picture.attach(params[:picture])
      redirect_to(club_path(@club))
    else
      flash[:warning] = "Veuillez insérer une image"
      redirect_to(club_path(@club.id))
    end
  end
  def show
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @events = Event.all
    @recrutements = Recrutement.all
        @clubs = Club.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@quarters = Quarter.all
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		
		puts "*"*60
		puts params
      if @user.update(first_name: params['first_name'] , last_name: params['last_name'], age: params['age'], description: params['description'], gender: params['gender'], pseudonym: params['pseudonym'], quarter: params['quarter'])
        
        puts "*"*60
		puts params
		flash[:success] = 'Votre profil a été mise à jour'
        redirect_to user_path
        
      else
      	flash[:success] = 'Il a eu une erreur dans votre action, veuillez réessayer'
        render '/users/:id/edit'
      end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/recrutements_helper.rb
module RecrutementsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/_footer.html.erb
<svg class="wave-top" viewBox="0 0 1439 147" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
   <g transform="translate(-1.000000, -14.000000)" fill-rule="nonzero">
     <g class="wave" fill="#f8fafc
">
       <path d="M1440,84 C1383.555,64.3 1342.555,51.3 1317,45 C1259.5,30.824 1206.707,25.526 1169,22 C1129.711,18.326 1044.426,18.475 980,22 C954.25,23.409 922.25,26.742 884,32 C845.122,37.787 818.455,42.121 804,45 C776.833,50.41 728.136,61.77 713,65 C660.023,76.309 621.544,87.729 584,94 C517.525,105.104 484.525,106.438 429,108 C379.49,106.484 342.823,104.484 319,102 C278.571,97.783 231.737,88.736 205,84 C154.629,75.076 86.296,57.743 0,32 L0,0 L1440,0 L1440,84 Z"></path>
     </g>
     <g transform="translate(1.000000, 15.000000)" fill="#FFFFFF
">
       <g transform="translate(719.500000, 68.500000) rotate(-180.000000) translate(-719.500000, -68.500000) ">
         <path d="M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496" opacity="0.100000001"></path>
         <path d="M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z" opacity="0.100000001"></path>
         <path d="M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z" opacity="0.200000003"></path>
       </g>
     </g>
   </g>
 </g>
</svg>
<!--Footer-->
<footer class="bg-gray">
  <div class="container mx-auto  px-8">

        <div class="w-full flex flex-col md:flex-row py-6">
        
      <div class="flex-1 mb-6">
      
       <%= link_to root_path do %>
          <%= image_tag "logo.svg", :size => "300x230" %>
       <% end %>
      </div>
    
    
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Links</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">FAQ</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Help</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Support</a>
                    </li>
                </ul>
            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Legal</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Terms</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Privacy</a>
                    </li>
                </ul>
            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Social</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Facebook</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Linkedin</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Twitter</a>
                    </li>
                </ul>
            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Company</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Official Blog</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">About Us</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-orange-500">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
  
  <a href="https://www.freepik.com/free-photos-vectors/background">Background vector created by freepik - www.freepik.com</a>

</footer>

app/views/static_pages/_form.html.erb
<%= form_with(model: static_page, local: true) do |form| %>
  <% if static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
        <% static_page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form', static_page: @static_page %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Malagasport</title>
  <meta name="Groupe03" content="Malagasport">
  

  <!-- Font Awesome if you need it-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
  
  <link rel="stylesheet" href="https://unpkg.com/tailwindcss/dist/tailwind.min.css">
  <!--Replace with your tailwind.css once created-->

  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700" rel="stylesheet">


      <!-- ==============================================
    CSS
    =============================================== -->
        <link type="text/css" href="/vendor/css/demos/photo.css" rel="stylesheet" />
        
    <!-- ==============================================
    Feauture Detection
    =============================================== -->
    <script src="/vendor/js/modernizr-custom.js"></script>

  <!-- Define your gradient here - use online tools to find a gradient matching your branding-->
  

</head>

<body class="leading-normal tracking-normal text-white gradient" style="font-family: 'Source Sans Pro', sans-serif;">





<!--effets riviere-->
<div class="relative -mt-12 lg:-mt-24">
  <svg viewBox="0 0 1428 174" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
  <g transform="translate(-2.000000, 44.000000)" fill="#FFFFFF" fill-rule="nonzero">
  <path d="M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496" opacity="0.100000001"></path>
  <path d="M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z" opacity="0.100000001"></path>
  <path d="M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z" id="Path-4" opacity="0.200000003"></path>
  </g>
  <g transform="translate(-4.000000, 76.000000)" fill="#FFFFFF" fill-rule="nonzero">
  <path d="M0.457,34.035 C57.086,53.198 98.208,65.809 123.822,71.865 C181.454,85.495 234.295,90.29 272.033,93.459 C311.355,96.759 396.635,95.801 461.025,91.663 C486.76,90.01 518.727,86.372 556.926,80.752 C595.747,74.596 622.372,70.008 636.799,66.991 C663.913,61.324 712.501,49.503 727.605,46.128 C780.47,34.317 818.839,22.532 856.324,15.904 C922.689,4.169 955.676,2.522 1011.185,0.432 C1060.705,1.477 1097.39,3.129 1121.236,5.387 C1161.703,9.219 1208.621,17.821 1235.4,22.304 C1285.855,30.748 1354.351,47.432 1440.886,72.354 L1441.191,104.352 L1.121,104.031 L0.457,34.035 Z"></path>
  </g>
  </g>
  </svg>
</div>




<section class="newsfeed">
    <div class="container-fluid">
     <div class="row">
      <div class="col-lg-3">
      <a href="<%= clubs_path%>">
     <div class="storybox" 
       style="background: linear-gradient( rgba(34,34,34,0.30), rgba(34,34,34,0.78)), url('vendor/club.jpeg') no-repeat;
              background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">
          <div class="story-body text-center">
           <div class=""><img class="img-circle" src="vendor/club.jpeg" alt="user"></div>
            <h3>club</h3>
          </div>      
     </div>
</a>
 <a href="<%= recrutements_path%>">
 <div class="storybox" 
       style="background: linear-gradient( rgba(34,34,34,0.30), rgba(34,34,34,0.78)), url('vendor/recrutement.jpeg') no-repeat;
              background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">

          <div class="story-body text-center">
           <div class=""><img class="img-circle" src="vendor/recrutement.jpeg" alt="user"></div>
            <h3>Recrutement</h3>
          </div>      
     </div>
</a>

 <a href="<%= events_path%>">
 <div class="storybox" 
       style="background: linear-gradient( rgba(34,34,34,0.30), rgba(34,34,34,0.78)), url('vendor/event.jpeg') no-repeat;
              background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">

          <div class="story-body text-center">
           <div class=""><img class="img-circle" src="vendor/event.jpeg" alt="user"></div>
            <h3>Evenement</h3>
          </div>      
     </div>
</a>

    



    
        <div class="trending-box hidden-xs hidden-md">
     <div class="row">
      <div class="col-lg-12">
        <a href="photo_stories.html"><h4>More stories</h4></a>
      </div>
     </div>
        </div>
     
    </div><!--/ col-lg-3 -->


      <div class="col-lg-6">
    









          <% eve = [] %>
          <% rec = [] %>
          <% clu = [] %>
            <% @events.each do |event| %>
            <% eve << event %>
            <%end%>

            <% @recrutements.each do |recrutement| %>
            <% rec << recrutement %>
            <%end%>

            <% @clubs.each do |club| %>
            <% clu << club %>
            <%end%>


            <% 5.times do |i| %>
 <div class="cardbox">
     
          <div class="cardbox-heading">
           <!-- START dropdown-->
           <div class="dropdown pull-right">
             <%= link_to "afficher", event_path(eve[(i+1)*(-1)].id), :class=>"btn btn-info" %> 
           
           </div><!--/ dropdown -->
           <!-- END dropdown-->
           <div class="media m-0">
            <div class="d-flex mr-3">
       <a href="#"><img class="img-responsive img-circle" src="vendor/event.jpeg" alt="User"></a>
      </div>
            <div class="media-body">
             <p class="m-0"><em>Evenement creer par: </em><strong class="a"><%= eve[(i+1)*(-1)].club.name %></strong></p>
             <style type="text/css">
               .a{
                font-size: 20px;
               }

               .b{
                text-align: center;
               }
             </style>
       <small><span>publié le <%= eve[(i+1)*(-1)].updated_at %></span></small>


            </div>
           </div><!--/ media -->
          </div><!--/ cardbox-heading -->
          
      <div class="cardbox-item">

      
          </div><!--/ cardbox-item -->
      <div class= "b">
        
          <h3><%= eve[(i+1)*(-1)].title%></h3>
          <p><%= eve[(i+1)*(-1)].description%></p>
          <strong><%= eve[(i+1)*(-1)].price%></strong>


      </div>
          <div class="cardbox-like">
       <ul>
      <li><a href="#"></a><span> like</span></li>
        <li><a href="#" title="" class="com"></a> <span class="span-last">comment</span></li>
       </ul>
          </div><!--/ cardbox-like -->        
                
     </div><!--/ cardbox -->  





     <div class="cardbox">
     
          <div class="cardbox-heading">
           <!-- START dropdown-->
           <div class="dropdown pull-right">
          
         <%= link_to "afficher", recrutement_path(rec[(i+1)*(-1)].id), :class=>"btn btn-info" %> 
    
           
           </div><!--/ dropdown -->
           <!-- END dropdown-->
           <div class="media m-0">
            <div class="d-flex mr-3">
       <a href="#"><img class="img-responsive img-circle" src="vendor/recrutement.jpeg" alt="User"></a>
      </div>
            <div class="media-body">
             <p class="m-0"><strong class="a"><%= rec[(i+1)*(-1)].club.name %></strong><em>   recrute </em></p>
             <style type="text/css">
               .a{
                font-size: 20px;
               }

               .b{
                text-align: center;
               }
             </style>
       <small><span>publié le <%= rec[(i+1)*(-1)].updated_at %></span></small>


            </div>
           </div><!--/ media -->
          </div><!--/ cardbox-heading -->
          
      <div class="cardbox-item">

      
          </div><!--/ cardbox-item -->
      <div class= "b">
        
          <h3><%= rec[(i+1)*(-1)].content%></h3>
          <p> date limite d'inscription:    <strong><%= rec[(i+1)*(-1)].deadline%></strong></p>
     


      </div>
          <div class="cardbox-like">
       <ul>
      <li><a href="#"></a><span> like</span></li>
        <li><a href="#" title="" class="com"></i></a> <span class="span-last"> comment</span></li>
       </ul>
          </div><!--/ cardbox-like -->        
                
     </div><!--/ cardbox -->  





<%end%>

</div>




<div class="col-lg-3">

    
         <div class="suggestion-box full-width">
    <%= image_tag "goal.svg", :size => "480x230" %>
    </div> 
  <div class="suggestion-box full-width">
          <img class="w-full md:w-4/5 z-50" src="https://s.france24.com/media/display/42cf5e50-9c12-11e9-b060-005056a964fe/w:1024/p:16x9/22062019_madagascar_guinee_resultats_poule_b_2.jpg">
    </div> 


        <div class="trending-box">
     <div class="row">
      <div class="col-lg-12">
        <h2>PARTENAIRES</h2>
      </div>
     </div>
        </div>
    
        <div class="trending-box">
          <img src="/vendor/a.jpg">
        </div>
        <div class="trending-box">
          <img src="/vendor/b.jpg">
        </div>
        <div class="trending-box">
          <img src="/vendor/c.jpg">
        </div>
        <div class="trending-box">
          <img src="/vendor/d.jpg">
        </div>
        <div class="trending-box">
          <img src="/vendor/e.jpg">
        </div>

    
    
    </div></div></div>



</section>






















  <!-- jQuery if you need it
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  -->

<script>

  var scrollpos = window.scrollY;
  var header = document.getElementById("header");
  var navcontent = document.getElementById("nav-content");
  var navaction = document.getElementById("navAction");
  var brandname = document.getElementById("brandname");
  var toToggle = document.querySelectorAll(".toggleColour");

  document.addEventListener('scroll', function() {

  /*Apply classes for slide in bar*/
  scrollpos = window.scrollY;

    if(scrollpos > 10){
      header.classList.add("bg-white");
    navaction.classList.remove("bg-white");
    navaction.classList.add("gradient");
    navaction.classList.remove("text-gray-800");
    navaction.classList.add("text-white");
    //Use to switch toggleColour colours
      for (var i = 0; i < toToggle.length; i++) {
       toToggle[i].classList.add("text-gray-800");
     toToggle[i].classList.remove("text-white");
    }
    header.classList.add("shadow");
    navcontent.classList.remove("bg-gray-100");
    navcontent.classList.add("bg-white");
    }
    else {
    header.classList.remove("bg-white");
    navaction.classList.remove("gradient");
    navaction.classList.add("bg-white");
    navaction.classList.remove("text-white");
    navaction.classList.add("text-gray-800");
    //Use to switch toggleColour colours
      for (var i = 0; i < toToggle.length; i++) {
       toToggle[i].classList.add("text-white");
     toToggle[i].classList.remove("text-gray-800");
    }
    
    header.classList.remove("shadow");
    navcontent.classList.remove("bg-white");
    navcontent.classList.add("bg-gray-100");
    
    }

  });

  
</script>

<script>
  
  
  /*Toggle dropdown list*/
  /*https://gist.github.com/slavapas/593e8e50cf4cc16ac972afcbad4f70c8*/
  
  var navMenuDiv = document.getElementById("nav-content");
  var navMenu = document.getElementById("nav-toggle");
  
  document.onclick = check;
  function check(e){
    var target = (e && e.target) || (event && event.srcElement);
    
    //Nav Menu
    if (!checkParent(target, navMenuDiv)) {
    // click NOT on the menu
    if (checkParent(target, navMenu)) {
      // click on the link
      if (navMenuDiv.classList.contains("hidden")) {
      navMenuDiv.classList.remove("hidden");
      } else {navMenuDiv.classList.add("hidden");}
    } else {
      // click both outside link and outside menu, hide menu
      navMenuDiv.classList.add("hidden");
    }
    }
    
  }
  function checkParent(t, elm) {
    while(t.parentNode) {
    if( t == elm ) {return true;}
    t = t.parentNode;
    }
    return false;
  }
</script>


</body>

</html>

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form', static_page: @static_page %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>