config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  resources :requests
  resources :events
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :admin, class_name: 'User'
	belongs_to :quarter
	has_many :recrutements
	has_many :members, class_name: 'User'
	has_many :participants, through: :recrutements
	has_many :events
	has_one_attached :picture
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :club
end

app/models/quarter.rb
class Quarter < ApplicationRecord
	has_many :clubs
	has_many :users
end

app/models/recrutement.rb
class Recrutement < ApplicationRecord
	has_many :requests
	belongs_to :club
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :recrutement
	belongs_to :user
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         belongs_to :quarter, optional: true
         belongs_to :club, optional: true
         has_many :requests
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@quarters = Quarter.all
  	@clubs = Club.all
  	@events = Event.all
  	@recrutements = Recrutement.all
  	@requests = Request.all
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
        @club = Club.find(params[:id])
  end

  # GET /clubs/new
  def new 
    @user = current_user
        @quarters = Quarter.all
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
    @quarters = Quarter.all
  end

  # POST /clubs
  # POST /clubs.json
  def create
      @my_user = current_user.id
    @club = Club.create('name' => params[:name], 'category' => params[:category], quarter_id: params[:quarter_id])

  @club.admin_id =  @my_user

    respond_to do |format|
      if @club.save
        format.html { redirect_to new_club_picture_path(@club.id), notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])
    puts "*"*60
    puts params
    respond_to do |format|
      if @club.update(name: params['name'], category: params['category'])
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(name: params['name'], category: params['category'])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@quarters = Quarter.all
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		
		puts "*"*60
		puts params
      if @user.update(first_name: params['first_name'] , last_name: params['last_name'], age: params['age'], description: params['description'], gender: params['gender'], pseudonym: params['pseudonym'], quarter: params['quarter'])
        
        puts "*"*60
		puts params
		flash[:success] = 'Votre profil a été mise à jour'
        redirect_to user_path
        
      else
      	flash[:success] = 'Il a eu une erreur dans votre action, veuillez réessayer'
        render '/users/:id/edit'
      end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/recrutements_helper.rb
module RecrutementsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<button><%= link_to 'Club', clubs_path %></button>

<button><%= link_to 'Event', events_path %></button>

<button><%= link_to 'Quarter', quarters_path %></button>

<button><%= link_to 'Recrutement', recrutements_path %></button>

<button><%= link_to 'Request', requests_path %></button>

app/views/layouts/_club.html.erb
 <% a = 0 %>
<% @clubs.each do |club| %>

  <% if club.admin.id == current_user.id %>
  <h1><%= link_to 'Mon club', club_path(club.id) %></h1>
    
  <% else %>
    <% a+= 1%>
  <% end %>
<% end %>
<%if a == @clubs.count %>
  <h1><%= link_to 'Créer un club', new_club_path %></h1>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>MALAGASPORT</title>
  <meta name="description" content="description here">
  <meta name="keywords" content="keywords,here">
  <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet"> 
  <!--Replace with your tailwind.css once created-->
  <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application' %>
</head>

<body class="bg-gray-400 font-sans leading-normal tracking-normal">



  <nav class="flex items-center justify-between flex-wrap bg-white-800 p-6  w-full z-10 top-0 ">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <a class="text-white no-underline hover:text-white hover:no-underline" href="#">
       <%= link_to root_path do %>
          <%= image_tag "logo.svg", :size => "180x110" %>
       <% end %>
      </a>
    </div>
    <div class="block lg:hidden">
      <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-500 border-white-600 hover:text-white hover:border-white">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>

    </div>
    <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0" id="nav-content">

      <ul class="list-reset lg:flex justify-end flex-1 items-center">
<% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4' %>

          <%= link_to "Profil", user_path(current_user.id), :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4'%>

           <%= link_to "Liste des clubs", clubs_path , :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4'%>

           <%= link_to "Liste des recrutements", recrutements_path , :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4'%>
  <% else %>    
            <%= link_to "Se connecter", new_user_session_path,:class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4' %>     
            <%= link_to "S'inscrire", new_user_registration_path, :class=> 'inline-block text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4' %>   
      <% end %>
      </ul>
    </div>
  </nav>

  <!--Container-->
  <div class="container shadow-lg mx-auto bg-white mt-24 md:mt-18">

  </div>

  <script>
    //Javascript to toggle the menu
    document.getElementById('nav-toggle').onclick = function(){
      document.getElementById("nav-content").classList.toggle("hidden");
    }
  </script>

  <%= yield %>
  </body>
</html>