config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  resources :requests
  resources :events
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recrutement.rb
class Recrutement < ApplicationRecord
	has_many :requests
	belongs_to :club
end

app/controllers/recrutements_controller.rb
class RecrutementsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_recrutement, only: [:show, :edit, :update, :destroy]

  # GET /recrutements
  # GET /recrutements.json
  def index
    @recrutements = Recrutement.all
  end

  # GET /recrutements/1
  # GET /recrutements/1.json
  def show
      @recrutement = Recrutement.find(params[:id])
  end

  # GET /recrutements/new
  def new
    @recrutement = Recrutement.new('content' => params[:content], 'deadline' => params[:deadline])
 @club = Club.find(params['data_value'])

  end

  # GET /recrutements/1/edit
  def edit
  end

  # POST /recrutements
  # POST /recrutements.json
  def create
   
    @recrutement = Recrutement.create('content' => params[:content], 'deadline' => params[:deadline], club_id: params['club_id'])

    respond_to do |format|
      if @recrutement.save
        format.html { redirect_to @recrutement, notice: 'Recrutement was successfully created.' }
        format.json { render :show, status: :created, location: @recrutement }
      else
        format.html { render :new }
        format.json { render json: @recrutement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recrutements/1
  # PATCH/PUT /recrutements/1.json
  def update
    @recrutement = Recrutement.find(params[:id])
    respond_to do |format|
      if @recrutement.update(content: params['content'], deadline:['deadline'])
        format.html { redirect_to @recrutement, notice: 'Recrutement was successfully updated.' }
        format.json { render :show, status: :ok, location: @recrutement }
      else
        format.html { render :edit }
        format.json { render json: @recrutement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recrutements/1
  # DELETE /recrutements/1.json
  def destroy
    @recrutement.destroy
    respond_to do |format|
      format.html { redirect_to recrutements_url, notice: 'Recrutement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recrutement
      @recrutement = Recrutement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recrutement_params
      params.require(:recrutement).permit(content: params['content'], deadline:['deadline'])
    end
end

app/helpers/recrutements_helper.rb
module RecrutementsHelper
end

app/views/recrutements/_form.html.erb
<%= form_with(model: recrutement, local: true) do |form| %>
  <% if recrutement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recrutement.errors.count, "error") %> prohibited this recrutement from being saved:</h2>

      <ul>
        <% recrutement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form_tag url_for(action: 'create'), method: "recrutement" do %>
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

  <div class="field">
    <%= label_tag :content %>
    <%= text_area_tag :content, @recrutement.content  %>
  </div>
  <div class="field">
    <input type="hidden" name="club_id" value="<%=@club.id%>">
  </div>

  <div class="field">
    <%= label_tag :deadline %>
    <%= text_field_tag :deadline, @recrutement.deadline %>
  </div>

  <div class="actions">
    <%= submit_tag "creer recrutement" %>
  </div>
<% end %>
<% end %>

app/views/recrutements/_update.html.erb
   <%= form_tag url_for(action: 'update'), method: "patch" do |form|%>
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >


  <div class="field">
    <%= label_tag :content %>
    <%= text_area_tag :content, @recrutement.content %>
  </div>


   <div class="field">
    <%= label_tag :deadline %>
    <%= date_field_tag :deadline, @recrutement.deadline %>
  </div>
  

  
<div class="field">
    <input type="hidden" name="recrutement_id" value="<%= @recrutement.id%>">
  </div>



  <div class="actions">
    <%= submit_tag "Mettre à jour" %>
  </div>
<% end %>

app/views/recrutements/edit.html.erb
<h1>Editing Recrutement</h1>

<%= render 'update', recrutement: @recrutement %>

<%= link_to 'Show', @recrutement %> |
<%= link_to 'Back', recrutements_path %>

app/views/recrutements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recrutements</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recrutements.each do |recrutement| %>
      <tr>
        <td><%= recrutement.content %></td>
        <td><%= recrutement.deadline %></td>
        <td><%= link_to 'Show', recrutement %></td>

<% if current_user == recrutement.club.admin %>
        <td><%= link_to 'Edit', edit_recrutement_path(recrutement) %></td>
        <td><%= link_to 'Destroy', recrutement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/recrutements/new.html.erb
<h1>New Recrutement</h1>

<%= render 'form', recrutement: @recrutement %>

<%= link_to 'Back', recrutements_path %>

app/views/recrutements/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>



<p id="notice"><%= notice %></p>



<div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Hello! vous etes sur le recrutement du club  <%= @recrutement.club.name %> </h1>
      <p><strong>Deadline:</strong>
  <%= @recrutement.deadline %></p>
     
    </div>
  </div>



<%= link_to 'Edit', edit_recrutement_path(@recrutement) %> |
<%= link_to 'Back', root_path %>


          





  <br/>
<br/>
<br/>
<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container text-center">
        <h1 class="display-3 text-primary">Listes des demandes</h1>

<a class="demand btn btn-primary btn-lg" id="<%= @recrutement.id %>" href="#" role="button" >Postuler &raquo;</a>


 
        <p>pour acceder a la page d un demande clique sur son blue nom</p>
        </div>
      </div>
      
      <div class="container">
        <!-- Example row of columns -->
        <div class="row d-flex justify-content-around">

 <% @recrutement.requests.each do |request| %>
 <% if request.user.club == request.recrutement.club%>
 <%else%>
            <div class="col-md-5 border border-primary shadow p-3 mb-5 bg-white rounded">

                <h3>Nom demandeur: <%= link_to "#{request.user.first_name}", user_path(request.user.id) %>    <%= request.user.last_name %> </h3>
                <h3> <%= link_to "Afficher", request_path(request.id) %> </h3>

           <p>Age: <%= request.user.age %></p>
            </div>
            <% end %>
            <% end %>
            
        </div>

        <hr>

      </div> <!-- /container -->

        
  </main>


</body>
</html>